#!/bin/bash


ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	getStatus)
		
		for ix in $PACKAGE_LIST
		do
			echo "Not found"
		done
			
	;;

	
	installPackage)
		f=$(tempfile)
		/usr/share/zero-lliurex-beam-studio/beam-downloader.py $f
		apt-get install -y ${f}.deb

	;;

	remove)
		
		echo "Removing files..."
		pkgs_selected=0
		errors=0

		for ix in $PACKAGE_LIST
		do
			apt-get remove -y $ix
		done

	;;		
		
esac
exit 0
